### ISSUE TITLE
Maybe simply right shift multiresult that's it

### ISSUE THREAD

**Issue by Xyncgas** [lemire/fastrange#6]
why not simply
```
uint32_t random_bounded(uint32_t range) {
  uint64_t random32bit =  random32(); //32-bit random number 
  multiresult = random32bit * range;
  return multiresult >> 32;
}
```
The result will always be [0,range) while the likely hood for every integer is equal

**Comment by lemire** [comment]
> The result will always be [0,range) while the likely hood for every integer is equal

Not. It is not going to be equal. You have 2**32 values, and you bin them into range values. So each possible output value matches `2**32/range` values of random32bit. If range is a power of two, then it will work out, but it cannot work out when range is not a power of two because `2**32/range` is not an integer.

Please see the reference paper for a detailed discussion:

Daniel Lemire, [Fast Random Integer Generation in an Interval](https://arxiv.org/abs/1805.10941), ACM Transactions on Modeling and Computer Simulation, January 2019 Article No. 3 https://doi.org/10.1145/3230636

**Comment by Xyncgas** [comment]
If a random number is [0,s) -> s = 2^32
let's say that's x
let's say there's a function f = ```((uint64_t) x) >> 32```
f 1x = [0,1)
f 2x = [0,2)
f ax = [0,a)

**Comment by Xyncgas** [comment]
Yea. Thanks.
